import { useState, useEffect } from 'react';
import { Sparkles, BookOpen, Loader2, Play } from 'lucide-react';
import LoopBreaker3D from './LoopBreaker3D';

export default function ReflectionView({ userId }) {
  const [loops, setLoops] = useState([]);
  const [sessions, setSessions] = useState([]);
  const [maskingInsights, setMaskingInsights] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [activeLoop, setActiveLoop] = useState(null);

  useEffect(() => {
    const fetchReflections = async () => {
      try {
        const response = await fetch(`http://localhost:8000/api/v1/reflections/${userId}`);
        if (response.ok) {
          const data = await response.json();
          setLoops(data.loops || []);
          setSessions(data.sessions || []);
          setMaskingInsights(data.masking_insights || []);
        }
      } catch (error) {
        console.error("Failed to fetch reflections:", error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchReflections();
  }, []);

  if (activeLoop) {
    const scenarioData = {
      fact: { text: activeLoop.trigger },
      interpretation: { text: activeLoop.feeling, explanation: "An automatic thought generated by the trigger." },
      emotion: { text: "Overwhelm", explanation: "The physical result of the interpretation." },
      prediction: { text: "It will always be this way.", explanation: "Time blindness making the feeling permanent." },
      reaction: { text: activeLoop.behavior, explanation: "The automatic coping mechanism." }
    };
    
    return (
      <div className="fixed inset-0 z-50 bg-black">
        <LoopBreaker3D 
          onClose={() => setActiveLoop(null)} 
          scenario={scenarioData} 
        />
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full p-6 pt-12 max-w-md mx-auto overflow-y-auto pb-24">
      <div className="mb-8">
        <h2 className="text-2xl font-light text-text-main flex items-center gap-2">
          <Sparkles className="text-primary" size={24} />
          Reflections
        </h2>
        <p className="text-sm text-text-muted mt-2">Making sense of your patterns, gently.</p>
      </div>

      {isLoading ? (
        <div className="flex flex-col items-center justify-center py-20 text-text-muted">
          <Loader2 className="animate-spin mb-4 text-primary" size={32} />
          <p>Loading your cognitive history...</p>
        </div>
      ) : (
        <>
          {/* Loop Breaker UI */}
          <div className="mb-8">
            <h3 className="text-sm font-medium text-text-main uppercase tracking-wider mb-4 flex items-center gap-2">
              <Play size={16} className="text-[#95b8a2]" />
              Interactive Loop Reviews
            </h3>
            <p className="text-xs text-text-muted mb-4">Click any past loop to step inside the 3D space and practice breaking it.</p>
            {loops.length === 0 ? (
              <div className="bg-surface rounded-2xl p-6 shadow-sm border border-border text-center text-text-muted text-sm">
                No loops identified yet. Chat with Nova when you're stuck in a pattern!
              </div>
            ) : (
              <div className="flex flex-col gap-6">
                {loops.map(loop => (
                  <div 
                    key={loop.id} 
                    onClick={() => setActiveLoop(loop)}
                    className="bg-surface rounded-2xl p-5 shadow-sm border border-border hover:border-primary hover:shadow-md transition-all cursor-pointer group"
                  >
                    <div className="flex justify-between items-center mb-3">
                      <span className="text-[10px] text-text-muted uppercase tracking-wider">{new Date(loop.created_at).toLocaleDateString()}</span>
                      <div className="bg-primary/10 text-primary text-xs px-2 py-1 rounded-md opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1">
                        <Play size={10} /> Play 3D
                      </div>
                    </div>
                    
                    <div className="relative pl-6">
                      <div className="absolute left-[11px] top-3 bottom-4 w-px bg-border group-hover:bg-primary/30 transition-colors"></div>

                      <div className="relative mb-4">
                        <div className="absolute -left-6 top-1 w-[10px] h-[10px] rounded-full bg-[#95b8a2] border-2 border-surface"></div>
                        <p className="text-xs text-text-muted uppercase tracking-wide font-medium">Trigger</p>
                        <p className="text-sm text-text-main mt-1 bg-background py-2 px-3 rounded-lg border border-border line-clamp-2">{loop.trigger}</p>
                      </div>
                      
                      <div className="relative mb-4">
                        <div className="absolute -left-6 top-1 w-[10px] h-[10px] rounded-full bg-[#D97757] border-2 border-surface"></div>
                        <p className="text-xs text-text-muted uppercase tracking-wide font-medium">Reaction</p>
                        <p className="text-sm text-text-main mt-1 bg-background py-2 px-3 rounded-lg border border-border line-clamp-2">{loop.behavior}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Masking Mirror UI */}
          <div className="mb-8">
            <h3 className="text-sm font-medium text-text-main uppercase tracking-wider mb-4 flex items-center gap-2">
              <Sparkles size={16} className="text-[#d1b06b]" />
              The Masking Mirror
            </h3>
            {maskingInsights.length === 0 ? (
              <div className="bg-surface rounded-2xl p-6 shadow-sm border border-border text-center text-text-muted text-sm">
                No masking patterns detected yet. Talk to Nova more about your day!
              </div>
            ) : (
              <div className="flex flex-col gap-4">
                {maskingInsights.map(insight => (
                  <div key={insight.id} className="bg-surface rounded-2xl p-5 shadow-sm border border-[#D97757]/30 border-l-4 border-l-[#D97757]">
                    <h4 className="font-medium text-text-main text-sm mb-2">{insight.title}</h4>
                    <p className="text-sm text-text-muted italic">"{insight.insight_text}"</p>
                    <div className="mt-3 pt-3 border-t border-border/50 text-right">
                      <span className="text-[10px] text-text-muted uppercase tracking-wider">{new Date(insight.created_at).toLocaleDateString()}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Session Summaries */}
          <div>
            <h3 className="text-sm font-medium text-text-main flex items-center gap-2 mb-4">
              <BookOpen size={18} className="text-text-muted" />
              Recent Sessions
            </h3>
            
            <div className="flex flex-col gap-4">
              {sessions.length === 0 ? (
                <div className="text-center text-text-muted text-sm py-4">No recent sessions found.</div>
              ) : (
                sessions.map(session => (
                  <div key={session.id} className="bg-surface rounded-2xl p-4 shadow-sm border border-border hover:shadow-md transition-shadow cursor-pointer">
                    <div className="flex justify-between items-start mb-2">
                      <h4 className="font-medium text-text-main text-sm">{session.title}</h4>
                      <span className="text-xs text-text-muted bg-background px-2 py-1 rounded-md">{session.date}</span>
                    </div>
                    <p className="text-sm text-text-muted leading-relaxed">
                      {session.insights}
                    </p>
                  </div>
                ))
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
